provider:
  name: "vllm"
  base_url: "http://localhost:8000"
  timeout: "240s"

model:
  name: "Marco-o1-int4-GPTQ"
  parameters:
    temperature: 0
    max_tokens: 2048
    top_p: 0.9
  

classification:
  template:
    system: "你是一个经过良好训练的AI助手，你的名字是Marco-o1.由阿里国际数字商业集团的AI Business创造. ## 重要！！！！！ 当你回答问题时，你的思考应该在<Thought>内完成，<Output>内输出你的结果。 <Thought>应该尽可能是英文，但是有2个特例，一个是对原文中的引用，另一个是是数学应该使用 markdown格式，<Output>内的输出需要遵循用户输入的语言."

    user: "Classify medical testimonies into these categories: 0: no weight change mentioned. 1: drug-induced weight gain or weight gain mentioned IF no drug mentioned. 2: drug-induced weight loss or weight loss mentioned IF no drug mentioned. Think through your analysis step by step, then provide your classification number in <Output> tags. The review: {text}. Your classification only (0, 1 or 2):"
    
  parsing:
    # Answer extraction patterns compatible with Go regex
    answer_patterns:
      - "<Output>\\s*([012])\\s*</Output>"     # Primary pattern: digit between Output tags
      - "<Output>\\s*(?:classification|answer)\\s*(?:is\\s*)?:?\\s*([012])\\s*</Output>"  # With classification/answer prefix
      - "<Output>\\s*(?:.*?)?\\b([012])\\b\\s*</Output>"  # Any digit within Output tags
      - "\\b([012])\\s*$"  # Fallback: digit at end of response
    
    # Fallback patterns if no match found
    find: ["0", "1", "2"]
    default: "nan"

processing:
  workers: 20
  batch_size: 1

output:
  directory: "./thinking_results"
  format: "json"