# Qwen2.5 Medical Classification (Non-Thinking)
provider:
  name: "vllm"
  base_url: "http://localhost:8000"
  timeout: "600s"

model:
  name: "Mistral"  # or your specific Qwen2.5 model
  parameters:
    # Qwen2.5 optimized parameters for fast classification
    temperature: 0
    #max_tokens: 256
    #top_p: 0.1
    #top_k: 1
    #repetition_penalty: 1
    #presence_penalty: 0.0
    #seed: 42
    
    # Standard stopping
    #stop: ["[/INST]"]
    #skip_special_tokens: false
    #spaces_between_special_tokens: true

classification:
  template:
    system: |
      You are a english medical expert specialized in detecting drug-induced side effects from patient drug reviews.
    
    user: |
      Does this review mention drug-induced nausea and/or vomiting? Answer "1" for yes, "0" for no.

  field_mapping:
    input_text_field: "comment"
  
  parsing:
    # Simple parsing for non-thinking models
    #preserve_thinking: false
    
    # Direct classification patterns
    answer_patterns:
    
    # Fallback to simple find
    find: ["1","0"]
    fallback: "nan"
    
    # Case insensitive matching
    case_sensitive: false
    exact_match: false

processing:
  workers: 50  # Higher throughput for non-thinking
  batch_size: 1
  
  # Live metrics configuration
  #live_metrics:
  #  enabled: true
  #  metric: "accuracy"
  #  ground_truth: "label"

output:
  directory: "./test-SE"
  format: "parquet" 