provider:
  name: "vllm"
  base_url: "http://localhost:8000"
  timeout: "600s"

model:
  name: "Qwen3"
  parameters:
    temperature: 0.7
    #max_tokens: 2048
    top_p: 0.95
    top_k: 20
    presence_penalty: 1.5
    #repetition_penalty: 1.1
    #seed: 42
    #stop: ["<|im_end|>\n"]
    #skip_special_tokens: false
    #spaces_between_special_tokens: true
    guided_choice: ["0", "1", "2"]

classification:
  template:
    #system: "You are a medical expert specialized in detecting drug-induced weight changes."
    user: "Classify medical drug record about a medication into categories: \"0\" for no weight change mentioned, \"1\" for weight GAIN drug-induced or weight gain mentioned if no drug mentioned, \"2\" for weight LOSS drug-induced or weight loss mentioned if no drug mentioned. Testimony: >>> {REVIEW} <<<. Answer with classification number only:"
  

  field_mapping:
    input_text_field: "REVIEW"

  parsing:
    thinking_tags: "<think></think>"
    preserve_thinking: true
    answer_patterns:
      - "(?i)(?:final\\s+)?(?:classification|answer)\\s*(?:is\\s*)?:?\\s*([012])"
      - "(?i)classification\\s*:?\\s*([012])"
      - "\\b([012])\\s*$"
    find: ["0", "1", "2"]
    fallback: "nan"
    case_sensitive: false
    exact_match: false

processing:
  workers: 100
  batch_size: 1
  repeat: 1
  rate_limit: false
  live_metrics:
    enabled: true
    metric: "kappa"
    ground_truth: "WEIGHT_CHANGE"
    #average: "macro"

output:
  directory: "./results"
  format: "json"