provider:
  name: "vllm"
  base_url: "http://localhost:8000"
  timeout: "1200s"

model:
  name: "Qwen3"
  parameters:
    temperature: 0.6
    #max_tokens: 512
    #top_p: 0.95
    #top_k: 1
    presence_penalty: 1.5
    #seed: 42
    stop: ["<|im_end|>\n"]
    #skip_special_tokens: false
    #spaces_between_special_tokens: true

classification:
  template:
    system: |
      You are a medical expert specialized in detecting drug-induced side effects from patient drug reviews.
      
      Your task is to identify and extract only the side effects that are directly attributed to or likely caused by the medication mentioned in the review.
      
      Guidelines:
      - Focus on symptoms that appeared after starting the medication
      - Exclude pre-existing conditions or symptoms unrelated to the drug
      - Use medical terminology when possible
      - If no side effects are mentioned, respond with "none"
      - Do not provide explanation of your output, only comma-separated list of side effects.
    
    user: |
      Extract as a comma-separated list the drug-induced side effects from patient drug review.
      
      Examples:
      
      Review: "I started taking Lisinopril for my blood pressure 3 weeks ago. Since then, I've developed a persistent dry cough that keeps me awake at night. I also noticed some dizziness when I stand up quickly. The medication is working for my BP though."
      Your answer: "dry cough,dizziness,orthostatic hypotension"
      
      Review: "Been on Sertraline for 6 months now. Initially had some nausea and headaches for the first two weeks. My anxiety has improved significantly, but I've gained about 10 pounds and my libido has decreased considerably."
      Your answer: "nausea,headaches,weight gain,decreased libido"
      
      Review: "Metformin has been great for controlling my diabetes. No issues at all, blood sugar levels are stable. I feel much better overall."
      Your answer: "none"
      
      Review: "Started Atorvastatin last month. Experiencing severe muscle pain in my legs and weakness. Also having trouble sleeping. My cholesterol levels have improved but these side effects are concerning."
      Your answer: "muscle pain,muscle weakness,insomnia"
      
      Now extract the side effects from the following review above as a comma-separated list of side effect without any other text.
      
      The review to analyze : >>> {comment} <<<
      
      Your answer: 

  field_mapping:
    input_text_field: "comment"
  
  parsing:
    # Extract content after thinking block using regex pattern
    answer_patterns:
      - "(?s)/think.*?\\n\\n\\s*(.*?)\\s*$"
      - "(?s)/think.*?\\n\\n\\s*(.+)$"
    thinking_tags: "<think></think>"
    preserve_thinking: false

processing:
  workers: 1
  batch_size: 1
  repeat: 1
  rate_limit: false

output:
  directory: "./output_tests/qwen3"
  format: "parquet"