provider:
  name: "vllm"
  base_url: "http://localhost:8000"
  timeout: "600s"

model:
  name: "Qwen3"
  parameters:
    temperature: 0.7
    #max_tokens: 1024
    #top_p: 0.95
    #top_k: 1
    presence_penalty: 1
    #seed: 42
    stop: ["<|im_end|>\n"]
    #skip_special_tokens: false
    #spaces_between_special_tokens: true

classification:
  template:
    system: |
      You are a medical expert specialized in detecting drug-induced side effects from patient drug reviews.
      
      Your task is to identify and extract only the side effects that are directly attributed to or likely caused by the medication mentioned in the review.
      
      Guidelines:
      - Use medical terminology
      - If no side effects are mentioned, respond with "none"
      - Provide a concise comma-separated list without explanation
    
    user: |
      Extract the drug-induced side effects from this patient drug review:
      
      Review: {comment}
      
      Comma-separated list of side effects:
  
  parsing:
    # Extract content after thinking block using regex pattern
    answer_patterns:
      - ".*?think.*?/think.*?\\n\\n(.+)"
      - ".*?</think>.*?\\n\\n(.+)"
      - "<think>.*?</think>\\s*(.+)"
    thinking_tags: "<think></think>"
    preserve_thinking: false

processing:
  workers: 1
  batch_size: 1
  repeat: 1
  rate_limit: false

output:
  directory: "./results"
  format: "parquet"