provider:
  name: vllm
  base_url: http://localhost:8000
  timeout: 600s

model:
  name: your-model-name
  parameters:
    temperature: 0.7
    max_tokens: 1024
    top_p: 0.95

classification:
  template:
    system: |
      You are a medical text classifier. Analyze the provided medical testimony and classify it based on weight change mentions.
      
      Categories:
      - 0: No weight change mentioned
      - 1: Weight gain mentioned (drug-induced or general)
      - 2: Weight loss mentioned (drug-induced or general)
      
      Respond with only the category number (0, 1, or 2).
    
    user: |
      Medical Testimony Analysis
      
      Patient Information:
      - Patient ID: {PATIENT_ID}
      - Age: {age} years old
      - Gender: {GENDER}
      - Primary Drug: {drug}
      - Dosage: {dosage}mg
      - Duration: {duration} months
      - Medical Conditions: {conditions}
      - Other Medications: {other_meds}
      - BMI: {bmi}
      - Is Active Treatment: {is_active}
      
      Testimony Text:
      "{text}"
      
      Additional Context:
      - Side Effects Reported: {side_effects}
      - Effectiveness Rating: {effectiveness}/10
      - Doctor Notes: {doctor_notes}
      
      Based on this medical testimony (Item #{index}), classify the weight change category.

  parsing:
    find: ["0", "1", "2"]
    default: "0"
    fallback: "0"

processing:
  workers: 10
  batch_size: 100
  repeat: 1
  rate_limit: false
  live_metrics:
    enabled: true
    metric: kappa
    ground_truth: label

output:
  directory: results
  format: json 