provider:
  name: "llamacpp"
  base_url: "http://0.0.0.0:8080"
  timeout: "300s"


model:
  name: "Qwen2.5"  # or your specific Qwen2.5 model
  parameters:
    # Qwen2.5 optimized parameters for fast classification
    temperature: 1
    max_tokens: 512
    #top_p: 0.1
    #top_k: 1
    #repetition_penalty: 1
    #presence_penalty: 0.0
    #seed: 42
    
    # Standard stopping
    stop: ["<|im_end|>"]
    skip_special_tokens: false
    spaces_between_special_tokens: true

classification:
  template:
    system: |
      You are a medical expert specialized in detecting drug-induced side effects from patient drug reviews.
    
    user: |
      Extract the drug-induced side effects from the following patient drug review: ### {comment} ###. List them in medical terms ending with a star by a space, example : \"nausea diarrhea anxiety intestinal pain\" or "none". Your answer (only a list of medical terms separated by a comma):

  field_mapping:
    input_text_field: "comment"

  
  parsing:
    # Simple parsing for non-thinking models
    #preserve_thinking: false
    
    # Direct classification patterns
    answer_patterns:
    
    # Fallback to simple find
    find: []
    
    # Case insensitive matching
    case_sensitive: false
    exact_match: false

processing:
  workers: 10  # Higher throughput for non-thinking
  batch_size: 1
  
  # Live metrics configuration
  #live_metrics:
  #  enabled: true
  #  metric: "accuracy"
  #  ground_truth: "label"

output:
  directory: "./results/test-SE"
  format: "parquet" 