provider:
  name: "vllm"
  base_url: "http://0.0.0.0:8000"
  timeout: "2400s"

model:
  name: "DeepSeek-R1"
  parameters:
    temperature: 0.2
    max_tokens: 1028
    #top_p: 0.5
    #top_k: 20
    #repetition_penalty: 1.0
    #presence_penalty: 1.5
    #frequency_penalty: 0.0
    #seed: 19950709
    #skip_special_tokens: false
    #include_stop_str_in_output: true
    #stop: ["<|/im_end|>"]

classification:
  template:
    system: "You are a helpful and harmless assistant. You should think step-by-step, starting with \"<think>\n\"."
    user: "Classify medical drug record about a medication into categories: \"0\" for no weight change mentioned, \"1\" for weight GAIN drug-induced or weight gain mentioned if no drug mentioned, \"2\" for weight LOSS drug-induced or weight loss mentioned if no drug mentioned. Analyze step by step then provide classification number. Pay attention to finding weight gain and loss as less common. Testimony: ### {text} ###. Answer with classification number only:"
  
  parsing:
    thinking_tags: "<think></think>"
    preserve_thinking: true
    
    answer_patterns:
      - "</think>\\s*[\\n\\r]*\\s*(?:.*?)?(?:classification|answer)\\s*(?:is\\s*)?:?\\s*([012])"
      - "</think>\\s*[\\n\\r]*\\s*(?:.*?)?\\b([012])\\b"
      - "(?i)(?:final\\s+)?(?:classification|answer)\\s*(?:is\\s*)?:?\\s*([012])"
      - "(?i)classification\\s*:?\\s*([012])"
      - "\\b([012])\\s*$"
    
    find: ["0", "1", "2"]
    fallback: "nan"
    case_sensitive: false
    exact_match: false

processing:
  workers: 100
  batch_size: 1
  repeat: 1
  rate_limit: false
  
  live_metrics:
    enabled: true
    metric: "kappa"
    ground_truth: "label"
    average: "macro"

output:
  directory: "./results"
  format: "json"